### PR TITLE
Fix API URL

### PR DESCRIPTION
**Pull request by JameelKaisar**
The previous URL was not working properly.
The URL on [CodePen](https://codepen.io/cfjedimaster/pen/BmgzeM) also needs to be changed.

### CODE REVIEW

**Comment by JameelKaisar** [comment]
The URL on [CodePen](https://codepen.io/cfjedimaster/pen/BmgzeM) also needs to be changed.

**Comment by Jinjiang** [comment]
@cfjedimaster would you mind taking a look at this PR and the corresponding CodePen of yours? Thanks.

**Comment by cfjedimaster** [comment]
Hmm, the API isn't responding. Let me check w/ Netlify.

**Comment by cfjedimaster** [comment]
So - the site is up and running. When I hit the function, I get no response. I haven't looked at the code for the site in 3 years. So yeah, this PR should be accepted as the URL -is- fixed, but the actual function isn't reliable anymore. I'd probably suggest rewriting the demo to hit a fake API so we aren't reliant on an external site.

**Comment by JameelKaisar** [comment]
Sorry, I didn't quite understand what you mean by hitting a fake API. Can you explain a bit more?

**Comment by cfjedimaster** [comment]
Instead of hitting a 'real' API, we run a method that has a fake delay, lets say 2 seconds, and returns static data (well, dynamic based on name, if i remember correctly how the old function worked).

**Comment by JameelKaisar** [comment]
You mean something like this?
```
async function validator(text) {
  return new Promise(resolve => setTimeout(() => resolve(text.length >= 6 ? {
    status: 204,
    message: "OK"
  } : {
    status: 400,
    error: "Product name length should be greater than or equal to 6."
  }), 2000))
}

const app = new Vue({
  el: '#app',
  data: {
    errors: [],
    name: ''
  },
  methods: {
    checkForm: function(e) {
      e.preventDefault();

      this.errors = [];

      if (this.name === '') {
        this.errors.push('Product name is required.');
      } else {
        validator(this.name)
          .then(async res => {
            if (res.status === 204) {
              alert(res.message);
            } else if (res.status === 400) {
              this.errors.push(res.error);
            }
          });
      }
    }
  }
})
```

But I think since this code is under `Server-side Validation`, using a fake API isn't the best thing to do. But if you think using a fake API is still a better option (surely in the long run), I can commit the modified code.

**Comment by cfjedimaster** [comment]
Oh I feel dumb. I forgot the serverless function returns status 204 on success, with no content. The function is working fine as is, I just didn't realize. I saw just accept the PR and move on! :)

**Comment by JameelKaisar** [comment]
Can anyone having access of the [CodePen](https://codepen.io/cfjedimaster/pen/BmgzeM) modify the `apiUrl` from https://vuecookbook.netlify.com/.netlify/functions/product-name?name= to https://vuecookbook.netlify.app/.netlify/functions/product-name?name= ?

**Comment by cfjedimaster** [comment]
That's me - and done. :)

**Comment by JameelKaisar** [comment]
Thanks :)

**Review by Jinjiang — APPROVED** [review]

**Pull request merged**
