### PR TITLE
Update components.md

### PR DESCRIPTION
**Pull request by amirhoseinsalehi**
Fixed a logical issue on an input.

### CODE REVIEW

**Comment by Justineo** [comment]
Thank you but the original code is correct. `v-model` expects custom component emit the whole `value` to its parent.

**Comment by amirhoseinsalehi** [comment]
> Thank you but the original code is correct. `v-model` expects custom component emit the whole `value` to its parent.

No problem, the issue is where you pass the whole event to the value prop which doesn't work correctly(object passed as a value).

**Comment by Justineo** [comment]
The child component should do `$emit('input', value)` where `value` is string so the received `$event` as a string.

**Comment by amirhoseinsalehi** [comment]
Aha, You are right.

**Pull request closed without merging**
